/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

/**
 *
 * @author Abner
 */
public class GUI_Principal extends javax.swing.JFrame {

  private PanamaHitek_Arduino ino = new PanamaHitek_Arduino();

  String grados1;
  String grados2;
  String grados3;

  private SerialPortEventListener listener = new SerialPortEventListener() {
    @Override
    public void serialEvent(SerialPortEvent spe) {

    }
  };

  /**
   * Creates new form GUI_Principal
   */
  public GUI_Principal() {
    initComponents();
    this.setTitle("Hipatia I");
    this.setLocationRelativeTo(null);
    try {
      ino.arduinoRXTX("COM12", 9600, listener);
    } catch (ArduinoException ex) {
      Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    jLabel1 = new javax.swing.JLabel();
    panel_vista = new javax.swing.JPanel();
    btn_start = new javax.swing.JButton();
    btn_stop = new javax.swing.JButton();
    btn_pause = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel4 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    btn_init = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jSeparator3 = new javax.swing.JSeparator();
    jSeparator4 = new javax.swing.JSeparator();
    D11 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    txt_motor1 = new javax.swing.JSpinner();
    txt_motor2 = new javax.swing.JSpinner();
    txt_motor3 = new javax.swing.JSpinner();
    D12 = new javax.swing.JTextField();
    D13 = new javax.swing.JTextField();
    D14 = new javax.swing.JTextField();
    D21 = new javax.swing.JTextField();
    D22 = new javax.swing.JTextField();
    D23 = new javax.swing.JTextField();
    D24 = new javax.swing.JTextField();
    D31 = new javax.swing.JTextField();
    D32 = new javax.swing.JTextField();
    D33 = new javax.swing.JTextField();
    D34 = new javax.swing.JTextField();
    D41 = new javax.swing.JTextField();
    D42 = new javax.swing.JTextField();
    D43 = new javax.swing.JTextField();
    D44 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    I11 = new javax.swing.JTextField();
    I12 = new javax.swing.JTextField();
    I13 = new javax.swing.JTextField();
    I14 = new javax.swing.JTextField();
    I21 = new javax.swing.JTextField();
    I22 = new javax.swing.JTextField();
    I23 = new javax.swing.JTextField();
    I24 = new javax.swing.JTextField();
    I31 = new javax.swing.JTextField();
    I32 = new javax.swing.JTextField();
    I33 = new javax.swing.JTextField();
    I34 = new javax.swing.JTextField();
    jButton2 = new javax.swing.JButton();
    I41 = new javax.swing.JTextField();
    I42 = new javax.swing.JTextField();
    I43 = new javax.swing.JTextField();
    I44 = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    txt_pos1 = new javax.swing.JTextField();
    txt_pos2 = new javax.swing.JTextField();
    txt_pos3 = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu2 = new javax.swing.JMenu();
    menu_uso = new javax.swing.JMenuItem();
    menu_about = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
    jLabel1.setText("Hipatia I");

    panel_vista.setBackground(new java.awt.Color(204, 204, 255));

    javax.swing.GroupLayout panel_vistaLayout = new javax.swing.GroupLayout(panel_vista);
    panel_vista.setLayout(panel_vistaLayout);
    panel_vistaLayout.setHorizontalGroup(
      panel_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 331, Short.MAX_VALUE)
    );
    panel_vistaLayout.setVerticalGroup(
      panel_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 270, Short.MAX_VALUE)
    );

    btn_start.setText("Iniciar");

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_start, org.jdesktop.beansbinding.ELProperty.create("Comienza el movimiento del robot"), btn_start, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
    bindingGroup.addBinding(binding);

    btn_start.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_startActionPerformed(evt);
      }
    });

    btn_stop.setText("Detener");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_stop, org.jdesktop.beansbinding.ELProperty.create("Detiene el movimiento total del robot"), btn_stop, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
    bindingGroup.addBinding(binding);

    btn_stop.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_stopActionPerformed(evt);
      }
    });

    btn_pause.setText("Pausar");
    btn_pause.setEnabled(false);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_pause, org.jdesktop.beansbinding.ELProperty.create("Pausa el movimiento del robot para reanudarse posteriormente"), btn_pause, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
    bindingGroup.addBinding(binding);

    jLabel2.setText("Controles generales");

    jLabel3.setText("Modelo Directo");

    jLabel4.setText("Modelo Inverso");

    btn_init.setText("Inicializar");
    btn_init.setToolTipText("Regresa el robot a su estado inicial");
    btn_init.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_initActionPerformed(evt);
      }
    });

    jLabel5.setText("Vista general del robot");

    D11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D11.setText("Cθi");

    jLabel6.setText("Motor 1");

    jLabel7.setText("Motor 2");

    jLabel8.setText("Motor 3");

    jLabel9.setText("°");

    jLabel10.setText("°");

    jLabel11.setText("°");

    D12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D12.setText("-Sθi");

    D13.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D13.setText("0");

    D14.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D14.setText("0");

    D21.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D21.setText("Sθi");

    D22.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D22.setText("Cθi");

    D23.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D23.setText("0");

    D24.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D24.setText("0");

    D31.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D31.setText("0");

    D32.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D32.setText("0");

    D33.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D33.setText("1");

    D34.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D34.setText("0");

    D41.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D41.setText("0");
    D41.setEnabled(false);

    D42.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D42.setText("0");
    D42.setEnabled(false);

    D43.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D43.setText("0");
    D43.setEnabled(false);

    D44.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D44.setText("1");
    D44.setEnabled(false);

    jButton1.setText("Ejecutar");
    jButton1.setToolTipText("Realiza el movimiento determinado por la matriz");

    I11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I11.setText("Cqi");

    I12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I12.setText("0");

    I13.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I13.setText("Sqi");

    I14.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I14.setText("0");

    I21.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I21.setText("Sqi");

    I22.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I22.setText("0");
    I22.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        I22ActionPerformed(evt);
      }
    });

    I23.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I23.setText("-Cqi");

    I24.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I24.setText("0");

    I31.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I31.setText("0");

    I32.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I32.setText("1");

    I33.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I33.setText("0");

    I34.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I34.setText("Ln");

    jButton2.setText("Ejecutar");
    jButton2.setToolTipText("Realiza el movimiento determinado por la matriz");

    I41.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I41.setText("0");
    I41.setEnabled(false);

    I42.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I42.setText("0");
    I42.setEnabled(false);

    I43.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I43.setText("0");
    I43.setEnabled(false);

    I44.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I44.setText("1");
    I44.setEnabled(false);

    jLabel12.setText("Posiciones");

    txt_pos1.setEditable(false);

    txt_pos2.setEditable(false);

    txt_pos3.setEditable(false);

    jLabel13.setText("Base");

    jLabel14.setText("Brazo");

    jLabel15.setText("Terminal");

    jMenu2.setText("Ayuda");

    menu_uso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
    menu_uso.setText("Modo de Uso");
    menu_uso.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menu_usoActionPerformed(evt);
      }
    });
    jMenu2.add(menu_uso);

    menu_about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
    menu_about.setText("Acerca de...");
    menu_about.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menu_aboutActionPerformed(evt);
      }
    });
    jMenu2.add(menu_about);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addGroup(layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel2))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(jLabel6)
                      .addComponent(jLabel7)
                      .addComponent(jLabel8))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                          .addComponent(txt_motor2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                          .addComponent(txt_motor3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                      .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_motor1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(43, 43, 43)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(btn_pause, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))))
              .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jButton1)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(D41)
                      .addComponent(D31)
                      .addComponent(D21)
                      .addComponent(D11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(D12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                      .addComponent(D22)
                      .addComponent(D32)
                      .addComponent(D42))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(D13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                      .addComponent(D23)
                      .addComponent(D33)
                      .addComponent(D43))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(D14)
                  .addComponent(D24)
                  .addComponent(D34)
                  .addComponent(D44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel4)
              .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(I41)
                  .addComponent(I31, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(I21, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(I11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jButton2)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(I12)
                      .addComponent(I22)
                      .addComponent(I32)
                      .addComponent(I42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(I13)
                      .addComponent(I23)
                      .addComponent(I33)
                      .addComponent(I43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(I14)
                      .addComponent(I24)
                      .addComponent(I34)
                      .addComponent(I44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(btn_init, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_stop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
          .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5)
              .addComponent(panel_vista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel12)
            .addGap(41, 41, 41)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txt_pos1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
              .addComponent(txt_pos2)
              .addComponent(txt_pos3))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel13)
              .addComponent(jLabel14)
              .addComponent(jLabel15))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(10, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(16, 16, 16)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel6)
              .addComponent(btn_start)
              .addComponent(btn_stop)
              .addComponent(jLabel9)
              .addComponent(txt_motor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel7)
                  .addComponent(jLabel10)
                  .addComponent(txt_motor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(txt_motor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel8)
                  .addComponent(jLabel11)))
              .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btn_pause)
                  .addComponent(btn_init))))
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addGroup(layout.createSequentialGroup()
                .addComponent(D11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(D21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(D31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(D41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(D12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(D22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(D32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(D42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(D13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(D23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(D33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(D43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(D14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(D24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(D34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(D44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(I11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(I21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(I31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(I41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(I12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(I22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(I32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(I42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(I13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(I23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(I33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(I43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(I14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(I24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(I34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(I44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panel_vista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel12)
            .addGap(1, 1, 1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jButton1)
              .addComponent(jButton2)))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txt_pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txt_pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel14))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt_pos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel15))
        .addGap(17, 17, 17))
    );

    bindingGroup.bind();

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void I22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I22ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_I22ActionPerformed

  private void menu_usoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_usoActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Instrucciones: \n"
            + "\t" + "Ingresa los grados que se moverá la parte del robot según se requiera\n"
            + "\t\t" + "El motor 1 se refiere a la base\n"
            + "\t\t" + "El motor 2 se refiere al brazo\n"
            + "\t\t" + "El motor 3 se refiere a la terminal\n\n\n"
            + "\t" + "Puedes ingresar los valores directamebte dentro del apartado \"Modelo Directo\" o \"Modelo Inverso\"\n"
            + "\t" + "para mover el robot según convenga");
  }//GEN-LAST:event_menu_usoActionPerformed

  private void menu_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aboutActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Proyecto realizado por:\nEfrén Mejía Ríos\ny\nAlfredo Abner González Mercado");
  }//GEN-LAST:event_menu_aboutActionPerformed

  private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
    // TODO add your handling code here:
    try {
      ino.killArduinoConnection();
      ino.arduinoRXTX("COM12", 9600, listener);
    } catch (ArduinoException ex) {
      Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btn_stopActionPerformed

  private void btn_initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_initActionPerformed
    // TODO add your handling code here:
    try {
      ino.killArduinoConnection();
      ino.arduinoRXTX("COM12", 9600, listener);
    } catch (ArduinoException ex) {
      Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btn_initActionPerformed

  private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
    // TODO add your handling code here:
    grados1 = txt_motor1.getValue() + ""; //Convierte el valor a cadena
    grados2 = txt_motor2.getValue() + "";
    grados3 = txt_motor3.getValue() + "";
    
    int grad1 = (int) txt_motor1.getValue();
    int grad2 = (int) txt_motor2.getValue();
    int grad3 = (int) txt_motor3.getValue();
    
    //System.out.println("Valor obtenido: "+grad1);
    if ((txt_motor1.getValue() + "").equals("")) {
      grados1 = "0";
    }else if(grad1 > 180 || grad1 < -180){
      txt_motor1.setValue(0);
      JOptionPane.showMessageDialog(null, "¡El valor no puede exceder los 180 grados positivos o negativos!", "Precaución", JOptionPane.WARNING_MESSAGE);
    }else{
      txt_pos1.setText(grados1+"°");
    }
    
    if ((txt_motor2.getValue() + "").equals("")) {
      grados2 = "0";
    }else if(grad2 > 180 || grad2 < -180){
      txt_motor2.setValue(0);
      JOptionPane.showMessageDialog(null, "¡El valor no puede exceder los 180 grados positivos o negativos!", "Precaución", JOptionPane.WARNING_MESSAGE);
    }else{
      txt_pos2.setText(grados2+"°");
    }
    
    if ((txt_motor3.getValue() + "").equals("")) {
      grados3 = "0";
    }else if(grad3 > 180 || grad3 < -180){
      txt_motor3.setValue(0);
      JOptionPane.showMessageDialog(null, "¡El valor no puede exceder los 180 grados positivos o negativos!", "Precaución", JOptionPane.WARNING_MESSAGE);
    }else{
      txt_pos3.setText(grados3+"°");
    }
    
    JOptionPane.showMessageDialog(null, "Realizando movimiento...","Mensaje",JOptionPane.PLAIN_MESSAGE);
  }//GEN-LAST:event_btn_startActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GUI_Principal().setVisible(true);
        JOptionPane.showMessageDialog(null, "Recuerda utilizar el menú de ayuda si no conoces el funcionamiento del programa\n\nAtajo: F1");
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField D11;
  private javax.swing.JTextField D12;
  private javax.swing.JTextField D13;
  private javax.swing.JTextField D14;
  private javax.swing.JTextField D21;
  private javax.swing.JTextField D22;
  private javax.swing.JTextField D23;
  private javax.swing.JTextField D24;
  private javax.swing.JTextField D31;
  private javax.swing.JTextField D32;
  private javax.swing.JTextField D33;
  private javax.swing.JTextField D34;
  private javax.swing.JTextField D41;
  private javax.swing.JTextField D42;
  private javax.swing.JTextField D43;
  private javax.swing.JTextField D44;
  private javax.swing.JTextField I11;
  private javax.swing.JTextField I12;
  private javax.swing.JTextField I13;
  private javax.swing.JTextField I14;
  private javax.swing.JTextField I21;
  private javax.swing.JTextField I22;
  private javax.swing.JTextField I23;
  private javax.swing.JTextField I24;
  private javax.swing.JTextField I31;
  private javax.swing.JTextField I32;
  private javax.swing.JTextField I33;
  private javax.swing.JTextField I34;
  private javax.swing.JTextField I41;
  private javax.swing.JTextField I42;
  private javax.swing.JTextField I43;
  private javax.swing.JTextField I44;
  private javax.swing.JButton btn_init;
  private javax.swing.JButton btn_pause;
  private javax.swing.JButton btn_start;
  private javax.swing.JButton btn_stop;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JMenuItem menu_about;
  private javax.swing.JMenuItem menu_uso;
  private javax.swing.JPanel panel_vista;
  private javax.swing.JSpinner txt_motor1;
  private javax.swing.JSpinner txt_motor2;
  private javax.swing.JSpinner txt_motor3;
  private javax.swing.JTextField txt_pos1;
  private javax.swing.JTextField txt_pos2;
  private javax.swing.JTextField txt_pos3;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables
}
