/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

/**
 *
 * @author Abner
 */
public class GUI_Principal extends javax.swing.JFrame {

  private PanamaHitek_Arduino ino = new PanamaHitek_Arduino();

  String grados1;
  String grados2;
  String grados3;

  int grados1_aux = 0;
  int grados2_aux = 0;
  int grados3_aux = 0;

  private SerialPortEventListener listener = new SerialPortEventListener() {
    @Override
    public void serialEvent(SerialPortEvent spe) {

    }
  };

  /**
   * Creates new form GUI_Principal
   */
  public GUI_Principal() {
    initComponents();
    this.setTitle("Hipatia I");
    this.setLocationRelativeTo(null);
    try {
      ino.arduinoRXTX("COM12", 9600, listener);
    } catch (ArduinoException ex) {
      Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    jLabel1 = new javax.swing.JLabel();
    panel_vista = new javax.swing.JPanel();
    btn_start = new javax.swing.JButton();
    btn_stop = new javax.swing.JButton();
    btn_stop.setBackground(Color.RED);
    btn_stop.setContentAreaFilled(false);
    btn_stop.setOpaque(true);
    btn_pause = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel4 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    btn_init = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jSeparator3 = new javax.swing.JSeparator();
    jSeparator4 = new javax.swing.JSeparator();
    D11 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    txt_motor1 = new javax.swing.JSpinner();
    txt_motor2 = new javax.swing.JSpinner();
    txt_motor3 = new javax.swing.JSpinner();
    D12 = new javax.swing.JTextField();
    D13 = new javax.swing.JTextField();
    D14 = new javax.swing.JTextField();
    D21 = new javax.swing.JTextField();
    D22 = new javax.swing.JTextField();
    D23 = new javax.swing.JTextField();
    D24 = new javax.swing.JTextField();
    D31 = new javax.swing.JTextField();
    D32 = new javax.swing.JTextField();
    D33 = new javax.swing.JTextField();
    D34 = new javax.swing.JTextField();
    D41 = new javax.swing.JTextField();
    D42 = new javax.swing.JTextField();
    D43 = new javax.swing.JTextField();
    D44 = new javax.swing.JTextField();
    I11 = new javax.swing.JTextField();
    I12 = new javax.swing.JTextField();
    I13 = new javax.swing.JTextField();
    I14 = new javax.swing.JTextField();
    I21 = new javax.swing.JTextField();
    I22 = new javax.swing.JTextField();
    I23 = new javax.swing.JTextField();
    I24 = new javax.swing.JTextField();
    I31 = new javax.swing.JTextField();
    I32 = new javax.swing.JTextField();
    I33 = new javax.swing.JTextField();
    I34 = new javax.swing.JTextField();
    I41 = new javax.swing.JTextField();
    I42 = new javax.swing.JTextField();
    I43 = new javax.swing.JTextField();
    I44 = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    txt_pos1 = new javax.swing.JTextField();
    txt_pos2 = new javax.swing.JTextField();
    txt_pos3 = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    jTextField5 = new javax.swing.JTextField();
    jTextField6 = new javax.swing.JTextField();
    jTextField7 = new javax.swing.JTextField();
    jTextField8 = new javax.swing.JTextField();
    jTextField9 = new javax.swing.JTextField();
    jTextField10 = new javax.swing.JTextField();
    jTextField11 = new javax.swing.JTextField();
    jTextField12 = new javax.swing.JTextField();
    jTextField13 = new javax.swing.JTextField();
    jTextField14 = new javax.swing.JTextField();
    jTextField15 = new javax.swing.JTextField();
    jTextField16 = new javax.swing.JTextField();
    jTextField17 = new javax.swing.JTextField();
    jTextField18 = new javax.swing.JTextField();
    jTextField19 = new javax.swing.JTextField();
    jTextField20 = new javax.swing.JTextField();
    jTextField21 = new javax.swing.JTextField();
    jTextField22 = new javax.swing.JTextField();
    jTextField23 = new javax.swing.JTextField();
    jTextField24 = new javax.swing.JTextField();
    jTextField25 = new javax.swing.JTextField();
    jTextField26 = new javax.swing.JTextField();
    jTextField27 = new javax.swing.JTextField();
    jTextField28 = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    jTextField29 = new javax.swing.JTextField();
    jTextField30 = new javax.swing.JTextField();
    jTextField31 = new javax.swing.JTextField();
    jTextField32 = new javax.swing.JTextField();
    jTextField33 = new javax.swing.JTextField();
    jTextField34 = new javax.swing.JTextField();
    jTextField35 = new javax.swing.JTextField();
    jTextField36 = new javax.swing.JTextField();
    jTextField37 = new javax.swing.JTextField();
    jTextField38 = new javax.swing.JTextField();
    jTextField39 = new javax.swing.JTextField();
    jTextField40 = new javax.swing.JTextField();
    jTextField41 = new javax.swing.JTextField();
    jTextField42 = new javax.swing.JTextField();
    jTextField43 = new javax.swing.JTextField();
    jTextField44 = new javax.swing.JTextField();
    jLabel18 = new javax.swing.JLabel();
    jTextField45 = new javax.swing.JTextField();
    jTextField46 = new javax.swing.JTextField();
    jTextField47 = new javax.swing.JTextField();
    jTextField48 = new javax.swing.JTextField();
    jSeparator5 = new javax.swing.JSeparator();
    jSeparator6 = new javax.swing.JSeparator();
    jSeparator7 = new javax.swing.JSeparator();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu2 = new javax.swing.JMenu();
    menu_uso = new javax.swing.JMenuItem();
    menu_about = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
    jLabel1.setText("Hipatia I");

    panel_vista.setBackground(new java.awt.Color(204, 204, 255));

    javax.swing.GroupLayout panel_vistaLayout = new javax.swing.GroupLayout(panel_vista);
    panel_vista.setLayout(panel_vistaLayout);
    panel_vistaLayout.setHorizontalGroup(
      panel_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 331, Short.MAX_VALUE)
    );
    panel_vistaLayout.setVerticalGroup(
      panel_vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 270, Short.MAX_VALUE)
    );

    btn_start.setText("Iniciar");

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_start, org.jdesktop.beansbinding.ELProperty.create("Comienza el movimiento del robot"), btn_start, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
    bindingGroup.addBinding(binding);

    btn_start.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_startActionPerformed(evt);
      }
    });

    btn_stop.setForeground(new java.awt.Color(255, 255, 255));
    btn_stop.setText("Detener");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_stop, org.jdesktop.beansbinding.ELProperty.create("Detiene el movimiento total del robot"), btn_stop, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
    bindingGroup.addBinding(binding);

    btn_stop.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_stopActionPerformed(evt);
      }
    });

    btn_pause.setText("Pausar");
    btn_pause.setEnabled(false);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_pause, org.jdesktop.beansbinding.ELProperty.create("Pausa el movimiento del robot para reanudarse posteriormente"), btn_pause, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
    bindingGroup.addBinding(binding);

    jLabel2.setText("Controles generales");

    jLabel3.setText("Modelo Directo");

    jLabel4.setText("Modelo Inverso");

    btn_init.setText("Inicializar");
    btn_init.setToolTipText("Regresa el robot a su estado inicial");
    btn_init.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_initActionPerformed(evt);
      }
    });

    jLabel5.setText("Vista general del robot");

    D11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D11.setText("Cθi");

    jLabel6.setText("Motor 1");

    jLabel7.setText("Motor 2");

    jLabel8.setText("Motor 3");

    jLabel9.setText("°");

    jLabel10.setText("°");

    jLabel11.setText("°");

    D12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D12.setText("-Sθi");

    D13.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D13.setText("0");

    D14.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D14.setText("0");

    D21.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D21.setText("Sθi");

    D22.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D22.setText("Cθi");

    D23.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D23.setText("0");

    D24.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D24.setText("0");

    D31.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D31.setText("0");

    D32.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D32.setText("0");

    D33.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D33.setText("1");

    D34.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D34.setText("0");

    D41.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D41.setText("0");
    D41.setEnabled(false);

    D42.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D42.setText("0");
    D42.setEnabled(false);

    D43.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D43.setText("0");
    D43.setEnabled(false);

    D44.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    D44.setText("1");
    D44.setEnabled(false);

    I11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I11.setText("Cqi");

    I12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I12.setText("0");

    I13.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I13.setText("Sqi");

    I14.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I14.setText("0");

    I21.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I21.setText("Sqi");

    I22.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I22.setText("0");
    I22.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        I22ActionPerformed(evt);
      }
    });

    I23.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I23.setText("-Cqi");

    I24.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I24.setText("0");

    I31.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I31.setText("0");

    I32.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I32.setText("1");

    I33.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I33.setText("0");

    I34.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I34.setText("Ln");

    I41.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I41.setText("0");
    I41.setEnabled(false);

    I42.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I42.setText("0");
    I42.setEnabled(false);

    I43.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I43.setText("0");
    I43.setEnabled(false);

    I44.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
    I44.setText("1");
    I44.setEnabled(false);

    jLabel12.setText("Posiciones");

    txt_pos1.setEditable(false);

    txt_pos2.setEditable(false);

    txt_pos3.setEditable(false);

    jLabel13.setText("Base");

    jLabel14.setText("Brazo");

    jLabel15.setText("Terminal");

    jLabel16.setText("Matriz transformación 1");

    jTextField19.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField19ActionPerformed(evt);
      }
    });

    jLabel17.setText("Matriz transformación 2");

    jLabel18.setText("Matriz transformación 3");

    jMenu2.setText("Ayuda");

    menu_uso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
    menu_uso.setText("Modo de Uso");
    menu_uso.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menu_usoActionPerformed(evt);
      }
    });
    jMenu2.add(menu_uso);

    menu_about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
    menu_about.setText("Acerca de...");
    menu_about.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menu_aboutActionPerformed(evt);
      }
    });
    jMenu2.add(menu_about);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel1)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel2))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(jLabel6)
                      .addComponent(jLabel7)
                      .addComponent(jLabel8))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                          .addComponent(txt_motor2)
                          .addComponent(txt_motor3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                      .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_motor1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(43, 43, 43)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(btn_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                      .addComponent(btn_init, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(btn_stop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel3))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(D31, javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(D21, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                      .addComponent(D11)
                      .addComponent(D41))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(D12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                      .addComponent(D22)
                      .addComponent(D32)
                      .addComponent(D42))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(D13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                      .addComponent(D23)
                      .addComponent(D33)
                      .addComponent(D43))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(D14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                      .addComponent(D24)
                      .addComponent(D34)
                      .addComponent(D44))))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel4)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(I21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(I11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(I31, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(I41))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                          .addComponent(I42, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addComponent(I43))
                        .addGroup(layout.createSequentialGroup()
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(I12)
                            .addGroup(layout.createSequentialGroup()
                              .addComponent(I32, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                              .addGap(1, 1, 1))
                            .addComponent(I22))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(I13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(I23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(I33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(I44)
                        .addComponent(I14)
                        .addComponent(I24)
                        .addComponent(I34, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                      .addGap(0, 22, Short.MAX_VALUE))))))
            .addGap(18, 18, 18))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel16)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
              .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
              .addComponent(jTextField6)
              .addComponent(jTextField10)
              .addComponent(jTextField14))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
              .addComponent(jTextField7)
              .addComponent(jTextField11)
              .addComponent(jTextField15))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
              .addComponent(jTextField12)
              .addComponent(jTextField16)
              .addComponent(jTextField4)))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
              .addComponent(jTextField29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField30, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField31, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField25, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
              .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
          .addComponent(jLabel17)
          .addComponent(jSeparator5)
          .addComponent(jSeparator6)
          .addComponent(jLabel18)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jTextField33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField42, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
              .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(jSeparator7))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(64, 64, 64)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5)
                .addComponent(panel_vista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel12)
            .addGap(41, 41, 41)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txt_pos1)
              .addComponent(txt_pos2)
              .addComponent(txt_pos3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel13)
              .addComponent(jLabel14)
              .addComponent(jLabel15))
            .addGap(69, 69, 69))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(jLabel6)
                      .addComponent(btn_start)
                      .addComponent(btn_stop)
                      .addComponent(jLabel9)
                      .addComponent(txt_motor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(jLabel7)
                          .addComponent(jLabel10)
                          .addComponent(txt_motor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(txt_motor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(jLabel8)
                          .addComponent(jLabel11)))
                      .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(btn_pause)
                          .addComponent(btn_init)))))))
              .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addGap(8, 8, 8)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(15, 15, 15)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(12, 12, 12)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(12, 12, 12)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(I12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(I13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(I14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(15, 15, 15)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addGroup(layout.createSequentialGroup()
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_pos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(I22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                      .addGap(12, 12, 12)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(I32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                      .addGap(12, 12, 12)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(I42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
              .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(65, 65, 65))
          .addGroup(layout.createSequentialGroup()
            .addGap(73, 73, 73)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panel_vista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 270, Short.MAX_VALUE)))
        .addGap(0, 0, 0))
    );

    bindingGroup.bind();

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void I22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I22ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_I22ActionPerformed

  private void menu_usoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_usoActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Instrucciones: \n"
            + "\t" + "Ingresa los grados que se moverá la parte del robot según se requiera\n"
            + "\t\t" + "El motor 1 se refiere a la base\n"
            + "\t\t" + "El motor 2 se refiere al brazo\n"
            + "\t\t" + "El motor 3 se refiere a la terminal\n\n\n"
            + "\t\t" + "Introduce los valores de movimiento en grados de movimiento según corresponda el motor\n\n"
            + "\t\t" + "El botón \"Detener\" sirve como paro de emergencia");
  }//GEN-LAST:event_menu_usoActionPerformed

  private void menu_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aboutActionPerformed
    // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Proyecto realizado por:\nEfrén Mejía Ríos\ny\nAlfredo Abner González Mercado");
  }//GEN-LAST:event_menu_aboutActionPerformed

  private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
    // TODO add your handling code here:
    try {
      ino.killArduinoConnection();
      ino.arduinoRXTX("COM12", 9600, listener);
    } catch (ArduinoException ex) {
      Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btn_stopActionPerformed

  private void btn_initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_initActionPerformed
    // TODO add your handling code here:
    try {
      ino.killArduinoConnection();
      ino.arduinoRXTX("COM12", 9600, listener);
    } catch (ArduinoException ex) {
      Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btn_initActionPerformed

  private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
    // TODO add your handling code here:

    grados1 = txt_motor1.getValue() + ""; //Convierte el valor a cadena
    grados2 = txt_motor2.getValue() + "";
    grados3 = txt_motor3.getValue() + "";

    int grad1_aux = (int) txt_motor1.getValue();
    int grad2_aux = (int) txt_motor2.getValue();
    int grad3_aux = (int) txt_motor3.getValue();

    //System.out.println("Valor obtenido: "+grad1);
    if ((txt_motor1.getValue() + "").equals("")) {
      grados1 = "0";
    } else {
      //grados1_aux = grados1_aux + grad1_aux;
      //txt_pos1.setText(grados1_aux + "°");
    }

    if ((txt_motor2.getValue() + "").equals("")) {
      grados2 = "0";
    } else {
      //grados2_aux = grados2_aux + grad2_aux;
      // txt_pos2.setText(grados2_aux + "°");
    }

    if ((txt_motor3.getValue() + "").equals("")) {
      grados3 = "0";
    } else {
      //grados3_aux = grados3_aux + grad3_aux;
      // txt_pos3.setText(grados3_aux + "°");
    }

    //Motor base no puede exceder 180° (90° en pos Inicial)
    //Motor Brazo no puede exceder 110° (~60° en pos Inicial)
    //Motor Terminal no puede exceder 180° (90° en pos Inicial)
    if (grados1_aux == 0 && grad1_aux <= 90) {
      grados1_aux = grados1_aux + grad1_aux;
      grados2_aux = grados2_aux + grad2_aux;
      grados3_aux = grados3_aux + grad3_aux;
      try {
        ino.sendData(grados1 + "," + grados2 + "," + grados3);
        System.out.println("Datos enviados: " + grados1 + "," + grados2 + "," + grados3);
        System.out.println("Grados a mostrar: " + grad1_aux + "," + grad2_aux + "," + grad3_aux);
        System.out.println("Suma de datos (base):" + grados1_aux);
        txt_pos1.setText(grados1_aux + "°");
        JOptionPane.showMessageDialog(null, "Realizando movimiento...", "Mensaje", JOptionPane.PLAIN_MESSAGE);
        if (ino.isMessageAvailable()) {
          System.out.println(ino.printMessage());
        }

      } catch (ArduinoException | SerialPortException ex) {
        Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
      }

    } else {
      if ((grados1_aux + grad1_aux) >= 180) {

        JOptionPane.showMessageDialog(null, "No se puede realizar el movimiento porque excede la capcidad del robot", "ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
      } else {
        grados1_aux = grados1_aux + grad1_aux;
        grados2_aux = grados2_aux + grad2_aux;
        grados3_aux = grados3_aux + grad3_aux;
        try {
          ino.sendData(grados1 + "," + grados2 + "," + grados3);
          System.out.println("Datos enviados: " + grados1 + "," + grados2 + "," + grados3);
          System.out.println("Grados a mostrar: " + grad1_aux + "," + grad2_aux + "," + grad3_aux);
          System.out.println("Suma de datos (base):" + grados1_aux);
          txt_pos1.setText(grados1_aux + "°");
          JOptionPane.showMessageDialog(null, "Realizando movimiento...", "Mensaje", JOptionPane.PLAIN_MESSAGE);
          if (ino.isMessageAvailable()) {
            System.out.println(ino.printMessage());
          }
        } catch (ArduinoException | SerialPortException ex) {
          Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }

    int theta1 = Integer.parseInt(grados1);
    int theta2 = Integer.parseInt(grados2);
    int theta3 = Integer.parseInt(grados3);
    
    double t1;
    t1 = Math.cos(5.73 - theta3) * Math.cos(180+theta1) * Math.cos(185.73+theta2)-Math.cos(90)*Math.sin(180+theta1)*Math.sin(185.73+theta2);
    
    double t2;
    t2 = (Math.cos(90)*Math.cos(185.73+theta2)*Math.sin(180+theta1)+Math.cos(180+theta1)*Math.sin(185.73+theta2))*Math.sin(5.73-theta3);
    
    double t3;
    t3 = 0;
    
    double t4;
    t4 = 350*Math.cos(5.73-theta3)*(Math.cos(180+theta1)*(0.184+Math.cos(185.73+theta2)) + 0.448074*Math.sin(180+theta1)*Math.sin(185.73+theta2));
    
    double t5;
    t5 = -(Math.cos(185.73+theta2)*Math.sin(180+theta1)+Math.cos(90)*Math.cos(180+theta1)*Math.sin(185.73+theta2))*Math.sin(5.73-theta3);
    
    double t6;
    t6 = Math.cos(5.73-theta3)*(Math.cos(90)*Math.cos(180+theta1)*Math.cos(185.73+theta2)-Math.sin(180+theta1)*Math.sin(185.73+theta2));
    
    double t7 = 0;
    
    double t8;
    t8 = -350*((0.184+Math.cos(185.73+theta2))*Math.sin(180+theta1)+Math.cos(90)*Math.cos(180+theta1)*Math.sin(185.73+theta2)*Math.sin(5.73-theta3));
    
    double t9 = 0;
    double t10 = 0;
    double t11 = Math.cos(90);
    double t12 = 0;
    double t13 = 0;
    double t14 = 0;
    double t15 = 0;
    double t16 = 1;
    D11.setText(Double.toString(t1));
    D12.setText(Double.toString(t2));
    D13.setText(Double.toString(t3));
    D14.setText(Double.toString(t4));
    D21.setText(Double.toString(t5));
    D22.setText(Double.toString(t6));
    D23.setText(Double.toString(t7));
    D24.setText(Double.toString(t8));
    D31.setText(Double.toString(t9));
    D32.setText(Double.toString(t10));
    D33.setText(Double.toString(t11));
    D34.setText(Double.toString(t12));
    D41.setText(Double.toString(t13));
    D42.setText(Double.toString(t14));
    D43.setText(Double.toString(t15));
    D44.setText(Double.toString(t16));
  }//GEN-LAST:event_btn_startActionPerformed

  private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField19ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GUI_Principal().setVisible(true);
        JOptionPane.showMessageDialog(null, "Recuerda utilizar el menú de ayuda si no conoces el funcionamiento del programa\n\nAtajo: F1");
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField D11;
  private javax.swing.JTextField D12;
  private javax.swing.JTextField D13;
  private javax.swing.JTextField D14;
  private javax.swing.JTextField D21;
  private javax.swing.JTextField D22;
  private javax.swing.JTextField D23;
  private javax.swing.JTextField D24;
  private javax.swing.JTextField D31;
  private javax.swing.JTextField D32;
  private javax.swing.JTextField D33;
  private javax.swing.JTextField D34;
  private javax.swing.JTextField D41;
  private javax.swing.JTextField D42;
  private javax.swing.JTextField D43;
  private javax.swing.JTextField D44;
  private javax.swing.JTextField I11;
  private javax.swing.JTextField I12;
  private javax.swing.JTextField I13;
  private javax.swing.JTextField I14;
  private javax.swing.JTextField I21;
  private javax.swing.JTextField I22;
  private javax.swing.JTextField I23;
  private javax.swing.JTextField I24;
  private javax.swing.JTextField I31;
  private javax.swing.JTextField I32;
  private javax.swing.JTextField I33;
  private javax.swing.JTextField I34;
  private javax.swing.JTextField I41;
  private javax.swing.JTextField I42;
  private javax.swing.JTextField I43;
  private javax.swing.JTextField I44;
  private javax.swing.JButton btn_init;
  private javax.swing.JButton btn_pause;
  private javax.swing.JButton btn_start;
  private javax.swing.JButton btn_stop;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JSeparator jSeparator7;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField10;
  private javax.swing.JTextField jTextField11;
  private javax.swing.JTextField jTextField12;
  private javax.swing.JTextField jTextField13;
  private javax.swing.JTextField jTextField14;
  private javax.swing.JTextField jTextField15;
  private javax.swing.JTextField jTextField16;
  private javax.swing.JTextField jTextField17;
  private javax.swing.JTextField jTextField18;
  private javax.swing.JTextField jTextField19;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField20;
  private javax.swing.JTextField jTextField21;
  private javax.swing.JTextField jTextField22;
  private javax.swing.JTextField jTextField23;
  private javax.swing.JTextField jTextField24;
  private javax.swing.JTextField jTextField25;
  private javax.swing.JTextField jTextField26;
  private javax.swing.JTextField jTextField27;
  private javax.swing.JTextField jTextField28;
  private javax.swing.JTextField jTextField29;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField30;
  private javax.swing.JTextField jTextField31;
  private javax.swing.JTextField jTextField32;
  private javax.swing.JTextField jTextField33;
  private javax.swing.JTextField jTextField34;
  private javax.swing.JTextField jTextField35;
  private javax.swing.JTextField jTextField36;
  private javax.swing.JTextField jTextField37;
  private javax.swing.JTextField jTextField38;
  private javax.swing.JTextField jTextField39;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField40;
  private javax.swing.JTextField jTextField41;
  private javax.swing.JTextField jTextField42;
  private javax.swing.JTextField jTextField43;
  private javax.swing.JTextField jTextField44;
  private javax.swing.JTextField jTextField45;
  private javax.swing.JTextField jTextField46;
  private javax.swing.JTextField jTextField47;
  private javax.swing.JTextField jTextField48;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private javax.swing.JTextField jTextField8;
  private javax.swing.JTextField jTextField9;
  private javax.swing.JMenuItem menu_about;
  private javax.swing.JMenuItem menu_uso;
  private javax.swing.JPanel panel_vista;
  private javax.swing.JSpinner txt_motor1;
  private javax.swing.JSpinner txt_motor2;
  private javax.swing.JSpinner txt_motor3;
  private javax.swing.JTextField txt_pos1;
  private javax.swing.JTextField txt_pos2;
  private javax.swing.JTextField txt_pos3;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables
}
